---
- name: get license details
  ## see: https://docs.ansible.com/ansible/latest/modules/uri_module.html
  uri:
    ## https://developer.github.com/enterprise/v3/enterprise-admin/license/#get-license-information
    url: "https://{{ ghe_host }}/api/v3/enterprise/settings/license"
    method: GET
    headers:
      Authorization: "token {{ ghe_token }}"
  register: ghe_license

- name: set license facts
  set_fact:
    expire_at: "{{ ghe_license.json.expire_at[:10] }}"
    expire_days: "{{ ((ghe_license.json.expire_at[:10] | to_datetime(fmt)) - (ansible_date_time.date[:19] | to_datetime(fmt))).days }}"
  vars:
    fmt: '%Y-%m-%d'

- name: send license email
  ## see: https://docs.ansible.com/ansible/latest/modules/mail_module.html
  mail:
    host: "{{ smtp_host }}"
    port: "{{ smtp_port }}"
    username: "{{ smtp_username }}"
    password: "{{ smtp_password }}"
    from: "{{ email_from }} (GHE License Mailer)"
    to: "{{ email_to }}"
    subject: "{{ email_company }}: GHE License usage report {{ ansible_date_time.date }}"
    body: "{{ lookup('template', 'email.html.j2') }}"
    subtype: html
